export enum TodosActionTypeEnum {
  API_TODOS_GET = 'API/TODOS/GET',
  TODOS_GET_START = 'TODOS/GET_START',
  TODOS_GET_ACCEPTED = 'TODOS/GET_ACCEPTED',
  TODOS_GET_DENIED = 'TODOS/GET_DENIED',

  API_TODO_ADD = 'API/TODOS/ADD',
  TODO_ADD_START = 'TODOS/ADD_START',
  TODO_ADD_ACCEPTED = 'TODOS/ADD_ACCEPTED',
  TODO_ADD_DENIED = 'TODOS/ADD_DENIED',
  API_TODOS_CLEAR_ADD_STATUS = 'API/TODOS/CLEAR_ADD_STATUS',

  API_TODO_DELETE = 'API/TODOS/DELETE',
}
